### ISSUE TITLE
Query on State Management

### ISSUE THREAD

**Issue by shafqat-ullah-dev** [kirill-zhirnov/nextjs-ecommerce-starter-kit#1]
Hi,

I've been reviewing the Next.js E-commerce Starter Kit and appreciate its structure. I noticed Redux isn't used for state management and am curious about this choice.

**State Management:** Could you briefly describe the state management approach used? Any specific libraries or patterns?

**No Redux:** What are the key reasons for not choosing Redux? Are there particular advantages with the chosen method?

Your insights would help deepen my understanding of alternative state management in Next.js projects.

Thanks for your contributions to the open-source community.

**Comment by kirill-zhirnov** [comment]
Hi @shafqatullah6342 ,
Thank you for the quetion!

In the repo the context is used to store cart and user details, pls see here: https://github.com/kirill-zhirnov/boundless-commerce-components/blob/master/src/components/CartContext.ts

The goal for the repo - to be a simple starter kit without complicated dependencies. You can setup redux or any other state management depends on your needs.
